require "bundler/gem_tasks"
require "minitest/test_task"
require "rubocop/rake_task"

Minitest::TestTask.create
RuboCop::RakeTask.new

RHO_SIG = File.expand_path("../rho/sig", __dir__)
RUNNER_SIG = File.expand_path("../rho-runner/sig", __dir__)
SDK_SIG = File.expand_path("../../../sdks/ruby/sig", __dir__)

desc "Validate the packaged RBS surface"
task :rbs do
  sh "bundle", "exec", "rbs", "-I", "sig", "-I", RHO_SIG, "-I", RUNNER_SIG, "-I", SDK_SIG, "validate"
end

task default: %i[test rubocop rbs]
