require "bundler/gem_tasks"
require "minitest/test_task"

Minitest::TestTask.create

require "rubocop/rake_task"

RuboCop::RakeTask.new

desc "Run offline browser lifecycle tests"
task :test_js do
  sh "bun", "test", "test/lifecycle_test.js", "test/scheduled_jobs_test.js", "test/artifact_lifecycle_test.js", "test/settings_test.js", "test/installation_test.js"
end

desc "Validate the packaged RBS surface"
task :rbs do
  sh "bundle", "exec", "rbs", "-I", "sig", "validate"
end

task default: %i[test test_js rubocop rbs]
