require "bundler/gem_tasks"
require "minitest/test_task"

Minitest::TestTask.create

require "rubocop/rake_task"

RuboCop::RakeTask.new

desc "Run offline browser lifecycle tests"
task :test_js do
  sh "bun", "test", "test/entrypoint_test.js", "test/lifecycle_test.js", "test/schedules_test.js", "test/artifact_lifecycle_test.js", "test/settings_test.js", "test/plugin_settings_test.js", "test/package_settings_test.js", "test/login_test.js", "test/conversation_usage_test.js", "test/composer_test.js", "test/reference_turn_test.js", "test/telegram_settings_test.js", "test/i18n_test.js", "test/context_overflow_test.js", "test/prompt_settings_test.js"
end

desc "Validate the packaged RBS surface"
task :rbs do
  sh "bundle", "exec", "rbs", "-I", "sig", "validate"
end

task default: %i[test test_js rubocop rbs]
