require "bundler/gem_tasks"
require "minitest/test_task"
require "rubocop/rake_task"
Minitest::TestTask.create
RuboCop::RakeTask.new

task :rbs do
  sh "bundle", "exec", "rbs", "-I", "sig", "-I", "../rho/sig", "-I", "../rho-runner/sig", "-I", "../../../sdks/ruby/sig", "validate"
end

task default: %i[test rubocop rbs]
