inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  TargetRubyVersion: 4.0

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBrackets: no_space

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: diff_comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: diff_comma

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never

Style/MissingElse:
  Enabled: true
  EnforcedStyle: case
