require_relative "api/errors"
require_relative "api/parsing"
require_relative "api/dispatch"
require_relative "api/results"
require_relative "api/unset"
require_relative "api/page"
require_relative "api/workspace_results"
require_relative "api/store_entry_results"
require_relative "api/one_shot_results"
require_relative "api/agent_loop_results"
require_relative "api/conversation_results"
require_relative "api/transcript_accumulator"
require_relative "api/thread_accumulator"
require_relative "api/workspace_projections"
require_relative "api/event_projections"
require_relative "api/workspaces"
require_relative "api/workspace_context"
require_relative "api/store_entries_context"
require_relative "api/one_shot_projections"
require_relative "api/one_shots_context"
require_relative "api/conversation_projections"
require_relative "api/conversation_history"
require_relative "api/conversations_context"
require_relative "api/conversation_context"
require_relative "api/inputs_context"
require_relative "api/scheduled_job_results"
require_relative "api/scheduled_job_projections"
require_relative "api/scheduled_jobs_context"
require_relative "api/conversation_turns_context"
require_relative "api/memory_context"
require_relative "api/prompt_documents_context"
require_relative "api/tool_lowering"
require_relative "api/agent_loop_projections"
require_relative "api/agent_loop_tasks_context"
require_relative "api/executor_inbox_context"
require_relative "api/upload_projections"
require_relative "api/executor_task_context"
require_relative "api/agent_loops_context"
require_relative "api/agent_loop_context"
require_relative "api/uploads_context"
require_relative "api/resource_link"
require_relative "api/tool_catalog"
require_relative "api/profile_context"
require_relative "api/agents_context"
require_relative "api/model_catalog"
require_relative "api/model_providers"
require_relative "api/executor_projections"
require_relative "api/executors"
require_relative "api/base_client"

module CybrosAgent
  # The Agent API family: bearer-only JSON resources under
  # `/agent_api/v1`. One bearer resolves to exactly one authorization plane,
  # so the planes are separate clients rather than one client with two moods —
  # a runner holds no member credential and must still be a complete citizen.
  module Api
  end
end
