#!/bin/sh
# Generated by install/stack/render.sh; edit the adjacent templates.
install_payload() {
  if [ ! -e compose.yaml ]; then
    cat > compose.yaml.new <<'CYBROS_PAYLOAD_EOF'
name: "${CYBROS_PROJECT_NAME:-cybros}"

x-logging: &logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

x-nexus: &nexus
  image: "${CYBROS_NEXUS_IMAGE_REPOSITORY:-jasl123/cybros-nexus}:${CYBROS_IMAGE_TAG:-latest}"
  entrypoint: []
  environment: &nexus-environment
    RAILS_ENV: production
    PGHOST: db
    PGUSER: postgres
    PGPASSWORD: "${POSTGRES_PASSWORD:?Missing POSTGRES_PASSWORD}"
    SECRET_KEY_BASE: "${SECRET_KEY_BASE:?Missing SECRET_KEY_BASE}"
    ACTIVE_RECORD_ENCRYPTION__PRIMARY_KEY: "${ACTIVE_RECORD_ENCRYPTION__PRIMARY_KEY:?Missing encryption key}"
    ACTIVE_RECORD_ENCRYPTION__DETERMINISTIC_KEY: "${ACTIVE_RECORD_ENCRYPTION__DETERMINISTIC_KEY:?Missing encryption key}"
    ACTIVE_RECORD_ENCRYPTION__KEY_DERIVATION_SALT: "${ACTIVE_RECORD_ENCRYPTION__KEY_DERIVATION_SALT:?Missing encryption salt}"
    NEXUS_SETUP_SECRET: "${NEXUS_SETUP_SECRET:-}"
    BASE_URL: "${CYBROS_NEXUS_URL:?Missing browser-reachable Nexus URL}"
    NEXUS_OAUTH_REDIRECT_URIS: '["${CYBROS_RHO_URL:?Missing browser-reachable rho URL}/auth/callback"]'
    NEXUS_OAUTH_ALLOW_HTTP: "${CYBROS_OAUTH_ALLOW_HTTP:-false}"
    SOLID_QUEUE_IN_PUMA: "false"
    THRUSTER_LOG_REQUESTS: "false"
  volumes:
    - ./data/nexus/storage:/rails/storage
  logging: *logging

services:
  # Prepare the image users' writable bind mounts once, including restored data.
  # PostgreSQL's official entrypoint prepares its own directory and UID.
  data_init:
    image: "${CYBROS_NEXUS_IMAGE_REPOSITORY:-jasl123/cybros-nexus}:${CYBROS_IMAGE_TAG:-latest}"
    user: "0:0"
    entrypoint: ["/bin/sh", "-c"]
    command:
      - "mkdir -p /data/nexus/storage /data/rho/home/tmp /data/rho/work && chown -R 1000:1000 /data/nexus/storage /data/rho/home /data/rho/work && chmod 700 /data/rho/home /data/rho/home/tmp"
    volumes:
      - ./data:/data
    restart: "no"
    logging: *logging

  db:
    image: "${CYBROS_POSTGRES_IMAGE:-postgres:18}"
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/18
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:?Missing POSTGRES_PASSWORD}"
    volumes:
      - ./data/postgres:/var/lib/postgresql
    healthcheck:
      test: [CMD-SHELL, "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 20s
    logging: *logging

  migrator:
    <<: *nexus
    depends_on:
      data_init:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    restart: "no"
    command: ["./bin/rails", "db:prepare"]

  nexus:
    <<: *nexus
    restart: unless-stopped
    depends_on: &nexus-dependencies
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    command: ["./bin/thrust", "./bin/rails", "server"]
    ports:
      - "${CYBROS_BIND:-127.0.0.1}:${CYBROS_NEXUS_PORT:-3300}:80"
    healthcheck:
      test: [CMD, curl, --fail, --silent, --max-time, "5", "http://127.0.0.1/up"]
      interval: 5s
      timeout: 6s
      retries: 24
      start_period: 30s

  jobs:
    <<: *nexus
    restart: unless-stopped
    depends_on: *nexus-dependencies
    command: ["./bin/jobs"]

  model_runner:
    <<: *nexus
    restart: unless-stopped
    depends_on: *nexus-dependencies
    stop_grace_period: 35s
    command: ["./bin/model_runner"]

  rho:
    image: "${CYBROS_RHO_IMAGE_REPOSITORY:-jasl123/cybros-rho}:${CYBROS_IMAGE_TAG:-latest}"
    restart: unless-stopped
    stop_grace_period: 30s
    depends_on:
      nexus:
        condition: service_healthy
    environment:
      RHO_MODE: full
      RHO_HOME: /var/lib/rho
      RHO_TOOLS_ROOT: /home/runner
      RHO_NEXUS_URL: http://nexus
      RHO_NEXUS_PUBLIC_URL: "${CYBROS_NEXUS_URL}"
      RHO_PUBLIC_URL: "${CYBROS_RHO_URL}"
      RHO_TELEGRAM_BOT_TOKEN: "${RHO_TELEGRAM_BOT_TOKEN:-}"
    command: [server, --bind, "0.0.0.0", --port, "7777", --unsafe-plaintext]
    working_dir: /home/runner
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${CYBROS_BIND:-127.0.0.1}:${CYBROS_RHO_PORT:-7777}:7777"
    volumes:
      - ./data/rho/home:/var/lib/rho
      - ./data/rho/work:/home/runner
    healthcheck:
      test: [CMD, curl, --fail, --silent, --max-time, "5", "http://127.0.0.1:7777/healthz"]
      interval: 5s
      timeout: 6s
      retries: 12
      start_period: 15s
    logging: *logging
CYBROS_PAYLOAD_EOF
    mv compose.yaml.new compose.yaml
  fi
  if [ ! -e deployment.compose.yaml ] || [ "$upgrade_manager" = yes ]; then
    cat > deployment.compose.yaml.new <<'CYBROS_PAYLOAD_EOF'
# Managed overlay: application activation writes both immutable references to
# images.env. Ordinary starts must use the same references as the updater.
x-nexus-image: &nexus-image
  image: "${CYBROS_NEXUS_IMAGE:-${CYBROS_NEXUS_IMAGE_REPOSITORY:-jasl123/cybros-nexus}:${CYBROS_IMAGE_TAG:-latest}}"

services:
  data_init:
    <<: *nexus-image
  migrator:
    <<: *nexus-image
  nexus:
    <<: *nexus-image
    environment:
      NEXUS_DEPLOYMENT_SOCKET: /run/cybros-updater/updater.sock
    volumes:
      - ./data/updater-ipc:/run/cybros-updater
  jobs:
    <<: *nexus-image
  model_runner:
    <<: *nexus-image
  rho:
    image: "${CYBROS_RHO_IMAGE:-${CYBROS_RHO_IMAGE_REPOSITORY:-jasl123/cybros-rho}:${CYBROS_IMAGE_TAG:-latest}}"
CYBROS_PAYLOAD_EOF
    mv deployment.compose.yaml.new deployment.compose.yaml
  fi
  if [ ! -e updater.compose.yaml ] || [ "$upgrade_manager" = yes ]; then
    cat > updater.compose.yaml.new <<'CYBROS_PAYLOAD_EOF'
# This owner survives application shutdown and has no published network port.
name: "${CYBROS_PROJECT_NAME:-cybros}-updater"

services:
  updater:
    image: "${CYBROS_UPDATER_IMAGE:-${CYBROS_UPDATER_IMAGE_REPOSITORY:-jasl123/cybros-updater}:${CYBROS_UPDATER_TAG:-latest}}"
    restart: unless-stopped
    environment:
      CYBROS_INSTALL_DIR: "${CYBROS_INSTALL_DIR:?Missing absolute installation directory}"
      CYBROS_NEXUS_IMAGE_REPOSITORY: "${CYBROS_NEXUS_IMAGE_REPOSITORY:-jasl123/cybros-nexus}"
      CYBROS_RHO_IMAGE_REPOSITORY: "${CYBROS_RHO_IMAGE_REPOSITORY:-jasl123/cybros-rho}"
      CYBROS_BACKUP_KEEP: "${CYBROS_BACKUP_KEEP:-3}"
      CYBROS_UPDATER_STATE_DIR: "${CYBROS_INSTALL_DIR}/data/updater"
      CYBROS_UPDATER_SOCKET: /run/cybros-updater/updater.sock
    volumes:
      - type: bind
        source: "${CYBROS_INSTALL_DIR}"
        target: "${CYBROS_INSTALL_DIR}"
      - ./data/updater-ipc:/run/cybros-updater
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: [CMD, ruby, /app/updater.rb, status]
      interval: 5s
      timeout: 8s
      retries: 12
      start_period: 10s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
CYBROS_PAYLOAD_EOF
    mv updater.compose.yaml.new updater.compose.yaml
  fi
  if [ ! -e cybros ] || [ "$upgrade_manager" = yes ]; then
    cat > cybros.new <<'CYBROS_PAYLOAD_EOF'
#!/bin/sh
# Local management for the installed stack. Configuration is Compose dotenv,
# never shell code: this script does not source an operator's environment file.
set -eu
umask 077

fail() { printf 'cybros: %s\n' "$*" >&2; exit 1; }
script_dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)
script_path=$script_dir/$(basename -- "$0")
stack_dir=$script_dir
if [ "${1:-}" = --dir ]; then
  [ "$#" -ge 2 ] || fail '--dir requires an existing installation directory'
  stack_dir=$(CDPATH='' cd -- "$2" && pwd -P) || fail 'Installation directory is unavailable'
  shift 2
fi
cd "$stack_dir"

compose() {
  set -- --env-file secrets.env -f compose.yaml -f deployment.compose.yaml "$@"
  if [ -f images.env ]; then set -- --env-file images.env "$@"; fi
  docker compose --env-file .env "$@"
}

updater_compose() {
  docker compose --env-file .env -f updater.compose.yaml "$@"
}

start_updater() {
  if ! updater_compose up -d "${1:---no-recreate}" --wait --wait-timeout "${CYBROS_WAIT_TIMEOUT:-240}"; then
    fail 'Upgrade manager did not become healthy. Run ./cybros manager logs; configuration and data were retained.'
  fi
}

updater_command() {
  updater_compose exec -T updater ruby /app/updater.rb "$@"
}

container_exec() {
  if [ -t 0 ] && [ -t 1 ]; then
    compose exec "$@"
  else
    compose exec -T "$@"
  fi
}

prerequisites() {
  command -v docker >/dev/null 2>&1 || fail 'Docker is required. Install Docker Engine with Compose, or Docker Desktop, then retry.'
  docker compose version >/dev/null 2>&1 || fail 'Docker Compose v2 is required.'
  docker info >/dev/null 2>&1 || fail 'The Docker daemon is unavailable. Start Docker or select a working Docker context, then retry.'
  docker compose up --help | grep -q -- --wait-timeout || fail 'Update Docker Compose: up --wait-timeout is required.'
}

setting() {
  # Generated values use single-quoted dotenv literals, including dollar signs.
  # This reader is for display only; Docker Compose parses the actual settings.
  sed -n "s/^$1='\(.*\)'$/\1/p" "${2:-.env}" | tail -n 1
}

write_setting() {
  case "$2" in *"'"*|*'
'*) fail "$1 must be a single line without single quotes" ;; esac
  printf "%s='%s'\n" "$1" "$2"
}

secret() {
  generated_secret=$(od -An -N32 -tx1 /dev/urandom | tr -d ' \n')
  [ "${#generated_secret}" -eq 64 ] || fail 'Could not read randomness from /dev/urandom'
  printf '%s' "$generated_secret"
}

initialize() {
  if [ ! -e secrets.env ] && [ -d data ]; then
    # Inspect only the top level: restored PostgreSQL children may belong to
    # its container user. An empty, pre-created data directory is a fresh install.
    for entry in data/* data/.[!.]* data/..?*; do
      if [ -e "$entry" ] || [ -L "$entry" ]; then
        fail 'Existing data has no secrets.env. Restore the original configuration from backup; new secrets cannot unlock this data.'
      fi
    done
  fi
  if { [ -e .env ] && [ ! -e secrets.env ]; } || { [ -e secrets.env ] && [ ! -e .env ]; }; then
    fail 'Only one configuration file exists. Restore the missing file from backup; secrets are never regenerated for an existing installation.'
  fi
  if [ ! -e .env ]; then
    backup_keep=${CYBROS_BACKUP_KEEP:-3}
    case "$backup_keep" in ''|*[!0-9]*|0*) fail 'CYBROS_BACKUP_KEEP must be a positive integer' ;; esac
    nexus_public_url=$(printf '%s' "${CYBROS_NEXUS_URL:-http://localhost:${CYBROS_NEXUS_PORT:-3300}}" | sed 's:/*$::')
    rho_public_url=$(printf '%s' "${CYBROS_RHO_URL:-http://localhost:${CYBROS_RHO_PORT:-7777}}" | sed 's:/*$::')
    case "$nexus_public_url $rho_public_url" in
      http://*|*' http://'*) oauth_http_default=true ;;
      *) oauth_http_default=false ;;
    esac
    {
      printf '# Compose configuration. Preserve secrets.env and the complete data/ directory.\n'
      write_setting CYBROS_PROJECT_NAME "${CYBROS_PROJECT_NAME:-cybros}"
      write_setting CYBROS_NEXUS_IMAGE_REPOSITORY "${CYBROS_NEXUS_IMAGE_REPOSITORY:-jasl123/cybros-nexus}"
      write_setting CYBROS_RHO_IMAGE_REPOSITORY "${CYBROS_RHO_IMAGE_REPOSITORY:-jasl123/cybros-rho}"
      write_setting CYBROS_UPDATER_IMAGE_REPOSITORY "${CYBROS_UPDATER_IMAGE_REPOSITORY:-jasl123/cybros-updater}"
      write_setting CYBROS_IMAGE_TAG "${CYBROS_IMAGE_TAG:-latest}"
      write_setting CYBROS_UPDATER_TAG "${CYBROS_UPDATER_TAG:-${CYBROS_IMAGE_TAG:-latest}}"
      write_setting CYBROS_BACKUP_KEEP "$backup_keep"
      if [ -n "${CYBROS_UPDATER_IMAGE:-}" ]; then write_setting CYBROS_UPDATER_IMAGE "$CYBROS_UPDATER_IMAGE"; fi
      if [ -n "${CYBROS_POSTGRES_IMAGE:-}" ]; then write_setting CYBROS_POSTGRES_IMAGE "$CYBROS_POSTGRES_IMAGE"; fi
      write_setting CYBROS_BIND "${CYBROS_BIND:-127.0.0.1}"
      write_setting CYBROS_NEXUS_PORT "${CYBROS_NEXUS_PORT:-3300}"
      write_setting CYBROS_RHO_PORT "${CYBROS_RHO_PORT:-7777}"
      write_setting CYBROS_NEXUS_URL "$nexus_public_url"
      write_setting CYBROS_RHO_URL "$rho_public_url"
      write_setting CYBROS_OAUTH_ALLOW_HTTP "${CYBROS_OAUTH_ALLOW_HTTP:-$oauth_http_default}"
    } > .env.new
    mv .env.new .env
  fi
  if [ ! -e secrets.env ]; then
    {
      printf '# Private deployment secrets. Back up with the database; never rotate encryption keys by reinstalling.\n'
      for key in POSTGRES_PASSWORD SECRET_KEY_BASE ACTIVE_RECORD_ENCRYPTION__PRIMARY_KEY ACTIVE_RECORD_ENCRYPTION__DETERMINISTIC_KEY ACTIVE_RECORD_ENCRYPTION__KEY_DERIVATION_SALT; do
        value=$(secret) || exit 1
        write_setting "$key" "$value"
      done
    } > secrets.env.new
    mv secrets.env.new secrets.env
  fi
  chmod 600 .env secrets.env
}

configured() {
  [ -f .env ] && [ -f secrets.env ] || fail 'Configuration is missing. Run the installer first; do not regenerate secrets for an existing database.'
  # Keep installation-file settings authoritative, even when this command is
  # launched from a shell used to install another stack.
  unset CYBROS_PROJECT_NAME CYBROS_NEXUS_IMAGE_REPOSITORY CYBROS_RHO_IMAGE_REPOSITORY CYBROS_UPDATER_IMAGE_REPOSITORY CYBROS_IMAGE_TAG CYBROS_UPDATER_TAG CYBROS_NEXUS_IMAGE CYBROS_RHO_IMAGE CYBROS_BIND CYBROS_NEXUS_PORT CYBROS_RHO_PORT CYBROS_NEXUS_URL CYBROS_RHO_URL CYBROS_OAUTH_ALLOW_HTTP
  unset CYBROS_BACKUP_KEEP CYBROS_UPDATER_IMAGE CYBROS_POSTGRES_IMAGE
  unset POSTGRES_PASSWORD SECRET_KEY_BASE ACTIVE_RECORD_ENCRYPTION__PRIMARY_KEY ACTIVE_RECORD_ENCRYPTION__DETERMINISTIC_KEY ACTIVE_RECORD_ENCRYPTION__KEY_DERIVATION_SALT NEXUS_SETUP_SECRET RHO_TELEGRAM_BOT_TOKEN
  CYBROS_INSTALL_DIR=$stack_dir
  export CYBROS_INSTALL_DIR
  compose config --quiet
}

start() {
  start_updater
  updater_command assert-idle
  if ! compose up -d --wait --wait-timeout "${CYBROS_WAIT_TIMEOUT:-240}"; then
    compose ps --all >&2 || true
    fail 'Startup did not become healthy. Run ./cybros logs; configuration and data were retained.'
  fi
  updater_command refresh-installed > /dev/null
}

recover_before_upgrade() {
  if ! CYBROS_UPDATER_IMAGE=$previous_manager updater_compose up -d --no-recreate --wait --wait-timeout "${CYBROS_WAIT_TIMEOUT:-240}"; then
    printf '%s\n' 'cybros: Could not restart the previous manager. Inspect ./cybros manager logs.' >&2
    return 1
  fi
  updater_command assert-idle || return 1
  if ! compose start --wait --wait-timeout "${CYBROS_WAIT_TIMEOUT:-240}"; then
    printf '%s\n' 'cybros: Could not restart the previous services. Inspect ./cybros logs.' >&2
    return 1
  fi
  updater_command refresh-installed > /dev/null
}

update_installation() {
  if [ "$backup" = true ]; then
    docker compose start --help | grep -q -- --wait-timeout || fail 'Update Docker Compose: start --wait-timeout is required for backup recovery.'
  fi
  start_updater
  updater_command assert-idle
  previous_manager=$(docker inspect --format '{{.Image}}' "$(updater_compose ps --quiet updater)")
  # Pins identify installed images, including local IDs in restored snapshots.
  # Compose's configured repository remains the new-release authority.
  manager_repository=$(CYBROS_UPDATER_IMAGE='' updater_compose config --images)
  case "$manager_repository" in ''|*'
'*) fail 'The manager Compose project must identify one image' ;; esac
  manager_repository=${manager_repository%@*}
  case "${manager_repository##*/}" in *:*) manager_repository=${manager_repository%:*} ;; esac
  manager_image=$manager_repository:$tag
  docker pull "$manager_image"
  release=$(docker image inspect --format '{{index .Config.Labels "org.opencontainers.image.version"}}' "$manager_image")
  case "$release" in
    [0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]) ;;
    *) fail 'The selected manager does not identify a published release' ;;
  esac
  [ "$tag" = latest ] || [ "$tag" = "$release" ] || fail 'The selected manager identifies a different release'
  manager_image=$(docker image inspect --format '{{if .RepoDigests}}{{index .RepoDigests 0}}{{else}}{{.Id}}{{end}}' "$manager_image")
  updater_command assert-idle
  if [ "$backup" = true ]; then
    if ! compose stop || ! updater_compose stop; then
      recover_before_upgrade || true
      fail 'Could not stop the installation for backup. Upgrade was not accepted.'
    fi
    if ! CYBROS_UPDATER_IMAGE=$previous_manager updater_compose run --rm --no-deps --pull never -T updater ruby /app/updater.rb backup; then
      recover_before_upgrade || true
      fail 'Installation backup failed. Upgrade was not accepted.'
    fi
    recover_before_upgrade || fail 'Backup completed, but the previous installation could not restart. Upgrade was not accepted.'
  fi
  if [ "$script_path" != "$stack_dir/cybros" ]; then
    cp "$script_path" cybros.new
    chmod 700 cybros.new
    mv cybros.new cybros
  fi
  # Only the manager selection changes here. Compose remains the dotenv parser;
  # unrelated configuration, secrets and operator overlays retain their bytes.
  cp -p .env .env.new
  sed '/^CYBROS_UPDATER_TAG=/d; /^CYBROS_UPDATER_IMAGE=/d' .env > .env.new
  write_setting CYBROS_UPDATER_TAG "$release" >> .env.new
  write_setting CYBROS_UPDATER_IMAGE "$manager_image" >> .env.new
  mv .env.new .env
  if ! updater_compose up -d --force-recreate --wait --wait-timeout "${CYBROS_WAIT_TIMEOUT:-240}"; then
    fail 'New manager failed readiness. Its selected image and state were retained. Inspect ./cybros manager logs and repair or retry. Application upgrade was not accepted.'
  fi
  set -- update "$release"
  if [ "$backup" = false ]; then set -- "$@" --no-backup; fi
  updater_command "$@"
}

shell_quote() {
  printf "'"
  printf '%s' "$1" | sed "s/'/'\\\\''/g"
  printf "'"
}

working_directory() {
  printf '  cd '
  shell_quote "$stack_dir"
  printf '\n'
}

instructions() {
  [ -f .env ] && [ -f secrets.env ] || fail 'Configuration is missing. Run the installer first.'
  console_url=$(setting CYBROS_RHO_URL)
  setup_secret=$(setting NEXUS_SETUP_SECRET secrets.env)
  printf '\nNext steps\n'
  working_directory
  printf '\n1. Open rho and choose Connect to Nexus:\n   %s\n' "$console_url"
  printf '\n2. Create your administrator account, then approve rho in the same browser tab.\n'
  printf '%s\n' '   Nexus returns you to rho automatically.'
  if [ -n "$setup_secret" ]; then
    encoded_secret=$(printf '%s' "$setup_secret" | od -An -v -tx1 | tr -d ' \n' | sed 's/../%&/g')
    setup_url="$(setting CYBROS_NEXUS_URL)/setup#setup_secret=$encoded_secret"
    printf '\n   This deployment has an optional setup secret configured:\n   Setup secret: %s\n' "$setup_secret"
    printf '\n   Private setup link: %s\n' "$setup_url"
    printf '%s\n' '   If you create the account using this separate link, return to rho and start Connect to Nexus again.'
  fi
  printf '\n3. Continue in rho Settings to configure models and optional Telegram.\n'
  printf '%s\n' '   Later visits use Connect to Nexus with your Nexus account; no separate rho password is needed.'
  printf '\nDevice login is also available from rho, or with ./cybros connect in a terminal.\n'
  printf '\nOptional terminal setup: ./cybros setup model or ./cybros setup telegram.\n'
  printf '\nUse ./cybros status to check services, or ./cybros instructions to see these steps again.\n'
  if [ "${1:-}" = open ] && [ -t 1 ] && [ -z "${SSH_CONNECTION:-}${SSH_TTY:-}" ]; then
    case "$(uname -s)" in
      Darwin) if command -v open >/dev/null 2>&1; then open "$console_url" >/dev/null 2>&1 || true; fi ;;
      Linux) if [ -n "${DISPLAY:-}${WAYLAND_DISPLAY:-}" ] && command -v xdg-open >/dev/null 2>&1; then xdg-open "$console_url" >/dev/null 2>&1 || true; fi ;;
      *) ;;
    esac
  fi
}

setup() {
  configured
  # The installer source may occupy stdin (curl | sh). The wizard must own a
  # real terminal, including Docker's TTY, without consuming shell source.
  if ! (exec 3<> /dev/tty) 2>/dev/null; then
    fail 'Setup needs an interactive terminal. Run ./cybros setup from a terminal; installed services and configuration were retained.'
  fi
  instructions
  if ! compose exec -e CMCTL_HOME=/var/lib/rho/cmctl rho rho setup \
    --nexus-url http://nexus --public-url "$(setting CYBROS_NEXUS_URL)" "$@" \
    </dev/tty >/dev/tty 2>&1; then
    fail 'Setup did not finish. Saved settings were retained; run ./cybros setup to continue.'
  fi
  # The running daemon applies Telegram configuration and owns its only poller.
  if ! compose exec -e CMCTL_HOME=/var/lib/rho/cmctl rho rho setup telegram --finish \
    </dev/tty >/dev/tty 2>&1; then
    fail 'Telegram setup did not finish. rho is running; use ./cybros setup telegram to continue.'
  fi
  printf '\nSetup complete. rho has applied the saved settings.\n'
}

usage() {
  printf '%s\n' 'Usage: ./cybros [--dir DIRECTORY] init|install|setup [model|telegram]|t3 [ARGS...]|instructions|up|status|logs [SERVICE]|stop|update [TAG] [--no-backup]|connect|rho [ARGS...]|cmctl [ARGS...]|compose [ARGS...]'
  printf '%s\n' 'init initializes configuration only; it never pulls images or starts services.'
  printf '%s\n' 'install initializes missing configuration, pulls images and starts; reruns preserve existing files.'
  printf '%s\n' 'update [TAG] backs up the stopped installation, updates its manager, then accepts and waits for the application upgrade with a database backup.'
  printf '%s\n' '--no-backup skips both backups. TAG defaults to latest and resolves to one UTC yyMMddHHmm release.'
  printf '%s\n' 'check [TAG] [--no-backup] prints the upgrade preflight report without accepting an upgrade.'
  printf '%s\n' 'backup and backups create/list private backups; stop the stack and manager first.'
  printf '%s\n' 'restore BACKUP_ID /absolute/empty/directory restores a stopped installation without starting it.'
  printf '%s\n' 'upgrade-status [ID], upgrade-log [ID] [CURSOR], and upgrade-resume ID inspect or recover an accepted upgrade.'
  printf '%s\n' 'update-manager pulls and restarts the separate upgrade manager using CYBROS_UPDATER_TAG.'
  printf '%s\n' 'manager [ARGS...] exposes its separate Docker Compose project, including manager logs.'
  printf '%s\n' 'instructions prints the rho URL and first-account setup steps without starting services.'
  printf '%s\n' 'setup configures Telegram, providers and the default model; saved settings apply immediately.'
  printf '%s\n' 'stop preserves containers and data. compose exposes normal Docker Compose commands.'
}

action=${1:-help}
[ "$#" -eq 0 ] || shift
case "$action" in
  help|--help|-h) usage; exit 0 ;;
esac
prerequisites
case "$action" in
  init)
    initialize
    configured
    printf '\nConfiguration ready. Services have not been started.\n'
    working_directory
    printf '%s\n' '  ./cybros install' 'Use ./cybros up instead if the images are already available locally.'
    printf '\nrho: %s\n' "$(setting CYBROS_RHO_URL)"
    printf '%s\n' 'After services start, open rho and choose Connect to Nexus. Run ./cybros instructions for first-account setup.'
    ;;
  install)
    [ "$#" -eq 0 ] || fail 'install takes no arguments'
    initialize
    configured
    updater_compose pull
    compose pull
    start
    printf '\nCybros services are healthy.\n'
    instructions open
    ;;
  up) configured; start; instructions ;;
  instructions) configured; instructions ;;
  setup) setup "$@" ;;
  t3)
    configured
    [ "$#" -gt 0 ] || set -- status
    case "${1:-status}" in
      local|host|secret)
        container_exec rho /opt/rho/libexec/t3-setup "$@"
        compose restart rho
        ;;
      project|create)
        container_exec rho /opt/rho/libexec/docker-entrypoint t3 "$@"
        compose restart rho
        ;;
      *) container_exec rho /opt/rho/libexec/docker-entrypoint t3 "$@" ;;
    esac
    ;;
  status) configured; compose ps --all; updater_compose ps --all ;;
  logs) configured; compose logs --tail 100 "$@" ;;
  stop)
    configured
    if [ -n "$(updater_compose ps --status running --quiet updater)" ]; then updater_command assert-idle; fi
    compose stop
    updater_compose stop
    ;;
  check|update)
    tag=latest
    tag_given=false
    backup=true
    for argument do
      case "$argument" in
        --no-backup) backup=false ;;
        *) [ "$tag_given" = false ] || fail "$action accepts one tag"; tag=$argument; tag_given=true ;;
      esac
    done
    case "$tag" in
      latest|[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]) ;;
      *) fail 'tag must be latest or a UTC yyMMddHHmm release tag' ;;
    esac
    configured
    if [ "$action" = update ]; then
      update_installation
    else
      start_updater
      set -- check "$tag"
      if [ "$backup" = false ]; then set -- "$@" --no-backup; fi
      updater_command "$@"
    fi
    ;;
  backup|backups)
    [ "$#" -eq 0 ] || fail "$action takes no arguments"
    configured
    updater_compose run --rm --no-deps --pull never -T updater ruby /app/updater.rb "$action"
    ;;
  restore)
    [ "$#" -eq 2 ] || fail 'restore requires BACKUP_ID and an existing empty absolute destination directory'
    configured
    case "$2" in /*) ;; *) fail 'restore destination must be absolute' ;; esac
    [ -d "$2" ] || fail 'restore destination must already exist'
    restore_directory=$(CDPATH='' cd -- "$2" && pwd -P)
    for entry in "$restore_directory"/* "$restore_directory"/.[!.]* "$restore_directory"/..?*; do
      if [ -e "$entry" ] || [ -L "$entry" ]; then fail 'restore destination must be empty'; fi
    done
    updater_compose run --rm --no-deps --pull never -T --volume "$restore_directory:$restore_directory" updater ruby /app/updater.rb restore "$1" "$restore_directory"
    ;;
  upgrade-status) configured; updater_command receipt "$@" ;;
  upgrade-log) configured; updater_command log "$@" ;;
  upgrade-resume) configured; updater_command resume "$@" ;;
  update-manager)
    configured
    start_updater
    updater_command assert-idle
    updater_compose pull
    start_updater --force-recreate
    ;;
  connect) configured; compose exec -T rho rho connect ;;
  rho) configured; compose exec -T rho rho "$@" ;;
  cmctl) configured; container_exec -e CMCTL_HOME=/var/lib/rho/cmctl rho cmctl "$@" ;;
  compose) configured; compose "$@" ;;
  manager) configured; updater_compose "$@" ;;
  *) usage >&2; fail "unknown command: $action" ;;
esac
CYBROS_PAYLOAD_EOF
    mv cybros.new cybros
  fi
  chmod 700 cybros
}
# Appended to the embedded templates by render.sh. Questions use /dev/tty,
# leaving stdin available for a piped installer.
install_fail() { printf 'Installer: %s\n' "$*" >&2; exit 1; }
install_cancel() { printf '\nInstallation cancelled. No files were changed.\n' >&2; exit 1; }

install_prompt() {
  printf '%s' "$1" >&3
  IFS= read -r answer <&3 || install_cancel
  [ -n "$answer" ] || answer=$2
}

install_port_valid() {
  case "$1" in ''|*[!0-9]*) return 1 ;; esac
  [ "${#1}" -le 5 ] && [ "$1" -ge 1 ] && [ "$1" -le 65535 ]
}

install_port() {
  while :; do
    install_prompt "$1 port [$2]: " "$2"
    if install_port_valid "$answer"; then
      # Decimal output avoids leading-zero interpretations in other tools.
      answer=$(printf '%s' "$answer" | sed 's/^0*//')
      return
    fi
    printf 'Enter a port from 1 to 65535.\n' >&3
  done
}

install_hostname() {
  while :; do
    install_prompt 'Server hostname or IPv4 address: ' ''
    case "$answer" in
      ''|*[!a-zA-Z0-9.-]*|[.-]*|*[.-]|0.0.0.0) printf 'Enter a hostname or IPv4 address, without a scheme, port or path.\n' >&3 ;;
      *) server_host=$answer; return ;;
    esac
  done
}

install_directory() {
  case "$install_dir" in
    '~') install_dir=$HOME ;;
    \~/*) install_dir=$HOME/${install_dir#\~/} ;;
    /*) ;;
    *) install_dir=$PWD/$install_dir ;;
  esac
  [ ! -e "$install_dir" ] || [ -d "$install_dir" ] || install_fail 'The installation path exists and is not a directory.'
  if [ -d "$install_dir" ]; then install_dir=$(CDPATH='' cd -- "$install_dir" && pwd); fi
  case "$install_dir" in '/'|*'
'*) install_fail 'Choose an installation directory other than /, on a single line.' ;; esac
}

install_prerequisites() {
  if ! command -v docker >/dev/null 2>&1; then
    case "$(uname -s)" in
      Darwin) printf '%s\n' 'Install Docker Desktop for Mac, open it, then run this installer again.' 'https://docs.docker.com/desktop/setup/install/mac-install/' >&2 ;;
      Linux) printf '%s\n' 'Install Docker Engine and the Docker Compose plugin for your Linux distribution, then run this installer again.' 'https://docs.docker.com/engine/install/' >&2 ;;
      *) printf '%s\n' 'Install Docker with Compose v2, then run this installer again.' 'https://docs.docker.com/get-started/get-docker/' >&2 ;;
    esac
    install_fail 'Docker was not found. This installer does not install Docker or run sudo.'
  fi
  docker compose version >/dev/null 2>&1 || install_fail 'Docker Compose v2 is missing. Install the Compose plugin (https://docs.docker.com/compose/install/) or update Docker Desktop, then retry.'
  docker info >/dev/null 2>&1 || install_fail 'Docker is not ready. Start Docker Desktop or Docker Engine, check your Docker context and permissions with docker info, then retry.'
  docker compose up --help | grep -q -- --wait-timeout || install_fail 'Update Docker Compose or Docker Desktop: compose up --wait-timeout is required.'
}

install_main() {
  set -eu
  umask 077
  install_dir=${CYBROS_INSTALL_DIR:-"$HOME/.local/share/cybros"}
  directory_set=${CYBROS_INSTALL_DIR:+yes}
  action=install
  unattended=no
  upgrade_manager=no
  while [ "$#" -gt 0 ]; do
    case "$1" in
      --help|-h)
        printf '%s\n' 'Usage: sh install.sh [--dir DIRECTORY] [--no-start] [--yes] [--upgrade-manager]' 'Interactive setup uses /dev/tty, including when the script is piped to sh.' '--yes uses environment settings and defaults without questions.' '--no-start prepares configuration without pulling images or starting services.' '--upgrade-manager replaces the cybros manager and its managed overlays; preserves compose.yaml, configuration, secrets and data.' 'Default directory: ~/.local/share/cybros. Requires Docker with Compose v2.'
        return 0
        ;;
      --dir) [ "$#" -ge 2 ] && [ -n "$2" ] || install_fail '--dir requires one nonempty directory'; install_dir=$2; directory_set=yes; shift 2 ;;
      --no-start) action=init; shift ;;
      --yes) unattended=yes; shift ;;
      --upgrade-manager) upgrade_manager=yes; shift ;;
      *) install_fail 'Usage: sh install.sh [--dir DIRECTORY] [--no-start] [--yes]' ;;
    esac
  done

  printf '\nCybros setup\n\n[1/5] Checking Docker\n'
  install_prerequisites
  printf '\n[2/5] Installation directory\n'
  install_directory
  if [ ! -e "$install_dir/.env" ] && [ ! -e "$install_dir/secrets.env" ] && [ "$unattended" = no ]; then
    # Test in a subshell first: a failed special-builtin redirection can exit sh.
    (exec 3<>/dev/tty) 2>/dev/null || install_fail 'Interactive setup needs a terminal. Run with --yes to use environment settings and defaults.'
    exec 3<>/dev/tty
    trap 'install_cancel' HUP INT TERM
    if [ -z "$directory_set" ]; then
      install_prompt "Installation directory [$install_dir]: " "$install_dir"
      install_dir=$answer
      install_directory
    fi
  fi
  printf 'Directory: %s\n' "$install_dir"

  if [ -e "$install_dir/.env" ] || [ -e "$install_dir/secrets.env" ]; then
    printf '\n[3/5] Keeping existing configuration\n'
    printf '%s\n' 'Existing configuration, secrets and data will be preserved. Setup questions are skipped.'
  else
    printf '\n[3/5] Network access\n'
    server_host=localhost
    if [ "$unattended" = no ]; then
      if [ -n "${CYBROS_BIND:-}${CYBROS_NEXUS_URL:-}${CYBROS_RHO_URL:-}" ]; then
        printf '%s\n' 'Using the network settings supplied in the environment.'
        if [ -z "${CYBROS_NEXUS_URL:-}" ] || [ -z "${CYBROS_RHO_URL:-}" ]; then
          case "${CYBROS_BIND:-127.0.0.1}:${CYBROS_NEXUS_URL:-}${CYBROS_RHO_URL:-}" in
            127.0.0.1:) ;;
            *) printf '%s\n' 'Choose the browser hostname for any URL not supplied above.'; install_hostname ;;
          esac
        fi
      else
        printf '%s\n' '1) This computer only (default)' '2) Home server or LAN'
        while :; do
          install_prompt 'Access [1]: ' 1
          case "$answer" in 1|2) break ;; *) printf 'Choose 1 or 2.\n' >&3 ;; esac
        done
        if [ "$answer" = 2 ]; then
          install_hostname
          CYBROS_BIND=0.0.0.0
          printf '%s\n' 'Both services will listen on all interfaces. Use these HTTP addresses on your trusted LAN.'
        fi
      fi
      if [ -z "${CYBROS_NEXUS_PORT:-}" ]; then
        install_port Nexus 3300
        CYBROS_NEXUS_PORT=$answer
      fi
      if [ -z "${CYBROS_RHO_PORT:-}" ]; then
        while :; do
          install_port rho 7777
          [ "$answer" != "$CYBROS_NEXUS_PORT" ] && break
          printf 'Use a different port from Nexus.\n' >&3
        done
        CYBROS_RHO_PORT=$answer
      fi
    fi
    CYBROS_BIND=${CYBROS_BIND:-127.0.0.1}
    CYBROS_NEXUS_PORT=${CYBROS_NEXUS_PORT:-3300}
    CYBROS_RHO_PORT=${CYBROS_RHO_PORT:-7777}
    install_port_valid "$CYBROS_NEXUS_PORT" || install_fail 'CYBROS_NEXUS_PORT must be a port from 1 to 65535.'
    install_port_valid "$CYBROS_RHO_PORT" || install_fail 'CYBROS_RHO_PORT must be a port from 1 to 65535.'
    [ "$CYBROS_NEXUS_PORT" -ne "$CYBROS_RHO_PORT" ] || install_fail 'Nexus and rho need different ports.'
    CYBROS_NEXUS_URL=${CYBROS_NEXUS_URL:-http://$server_host:$CYBROS_NEXUS_PORT}
    CYBROS_RHO_URL=${CYBROS_RHO_URL:-http://$server_host:$CYBROS_RHO_PORT}
    export CYBROS_BIND CYBROS_NEXUS_PORT CYBROS_RHO_PORT CYBROS_NEXUS_URL CYBROS_RHO_URL
  fi

  printf '\n[4/5] Review installation\n'
  printf 'Directory: %s\nData:      %s/data\n' "$install_dir" "$install_dir"
  if [ ! -e "$install_dir/.env" ] && [ ! -e "$install_dir/secrets.env" ]; then
    printf 'Nexus:     %s\nrho:       %s\nBind:      %s\nNexus image: %s:%s\nrho image:   %s:%s\n' "$CYBROS_NEXUS_URL" "$CYBROS_RHO_URL" "$CYBROS_BIND" "${CYBROS_NEXUS_IMAGE_REPOSITORY:-jasl123/cybros-nexus}" "${CYBROS_IMAGE_TAG:-latest}" "${CYBROS_RHO_IMAGE_REPOSITORY:-jasl123/cybros-rho}" "${CYBROS_IMAGE_TAG:-latest}"
    if [ "$unattended" = no ]; then
      if [ "$action" = init ]; then question='Create configuration? [Y/n]: '; else question='Install and start Cybros? [Y/n]: '; fi
      while :; do
        install_prompt "$question" y
        case "$answer" in y|Y|[Yy][Ee][Ss]) break ;; n|N|[Nn][Oo]) install_cancel ;; *) printf 'Answer yes or no.\n' >&3 ;; esac
      done
    fi
  fi
  trap - HUP INT TERM
  mkdir -p "$install_dir"
  install_dir=$(CDPATH='' cd -- "$install_dir" && pwd)
  [ "$install_dir" != / ] || install_fail 'Choose an installation directory other than /.'
  chmod 700 "$install_dir"
  if [ -e "$install_dir/cybros" ] || [ -e "$install_dir/compose.yaml" ]; then
    if [ "$upgrade_manager" = yes ]; then
      printf '%s\n' 'Refreshing cybros and the managed deployment overlays. Keeping the existing Compose file, configuration, secrets and data.'
    else
      printf '%s\n' 'Keeping the existing cybros manager and Compose file, including local changes.'
    fi
  fi
  (
    cd "$install_dir"
    install_payload
  )
  if [ "$action" = init ]; then
    printf '\n[5/5] Preparing configuration\n'
  else
    printf '\n[5/5] Pulling images and waiting for healthy services\n'
  fi
  "$install_dir/cybros" "$action" </dev/null
}

install_main "$@"
