#!/bin/sh
# Generated by install/stack/render.sh; edit the adjacent templates.
install_payload() {
  if [ ! -e compose.yaml ]; then
    cat > compose.yaml.new <<'CYBROS_PAYLOAD_EOF'
name: "${CYBROS_PROJECT_NAME:-cybros}"

x-logging: &logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

x-nexus: &nexus
  image: "${CYBROS_IMAGE_NAMESPACE:-jasl123}/cybros-nexus:${CYBROS_IMAGE_TAG:-latest}"
  entrypoint: []
  environment: &nexus-environment
    RAILS_ENV: production
    PGHOST: db
    PGUSER: postgres
    PGPASSWORD: "${POSTGRES_PASSWORD:?Missing POSTGRES_PASSWORD}"
    SECRET_KEY_BASE: "${SECRET_KEY_BASE:?Missing SECRET_KEY_BASE}"
    ACTIVE_RECORD_ENCRYPTION__PRIMARY_KEY: "${ACTIVE_RECORD_ENCRYPTION__PRIMARY_KEY:?Missing encryption key}"
    ACTIVE_RECORD_ENCRYPTION__DETERMINISTIC_KEY: "${ACTIVE_RECORD_ENCRYPTION__DETERMINISTIC_KEY:?Missing encryption key}"
    ACTIVE_RECORD_ENCRYPTION__KEY_DERIVATION_SALT: "${ACTIVE_RECORD_ENCRYPTION__KEY_DERIVATION_SALT:?Missing encryption salt}"
    NEXUS_SETUP_SECRET: "${NEXUS_SETUP_SECRET:?Missing setup secret}"
    BASE_URL: "${CYBROS_NEXUS_URL:?Missing browser-reachable Nexus URL}"
    SOLID_QUEUE_IN_PUMA: "false"
    THRUSTER_LOG_REQUESTS: "false"
  volumes:
    - ./data/nexus/storage:/rails/storage
  logging: *logging

services:
  # Prepare the image users' writable bind mounts once, including restored data.
  # PostgreSQL's official entrypoint prepares its own directory and UID.
  data_init:
    image: "${CYBROS_IMAGE_NAMESPACE:-jasl123}/cybros-nexus:${CYBROS_IMAGE_TAG:-latest}"
    user: "0:0"
    entrypoint: ["/bin/sh", "-c"]
    command:
      - "mkdir -p /data/nexus/storage /data/rho/home /data/rho/work && chown -R 1000:1000 /data/nexus/storage /data/rho/home /data/rho/work && chmod 700 /data/rho/home"
    volumes:
      - ./data:/data
    restart: "no"
    logging: *logging

  db:
    image: postgres:18
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/18
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:?Missing POSTGRES_PASSWORD}"
    volumes:
      - ./data/postgres:/var/lib/postgresql
    healthcheck:
      test: [CMD-SHELL, "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 20s
    logging: *logging

  migrator:
    <<: *nexus
    depends_on:
      data_init:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    restart: "no"
    command: ["./bin/rails", "db:prepare"]

  nexus:
    <<: *nexus
    restart: unless-stopped
    depends_on: &nexus-dependencies
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    command: ["./bin/thrust", "./bin/rails", "server"]
    ports:
      - "${CYBROS_BIND:-127.0.0.1}:${CYBROS_NEXUS_PORT:-3300}:80"
    healthcheck:
      test: [CMD, curl, --fail, --silent, --max-time, "5", "http://127.0.0.1/up"]
      interval: 5s
      timeout: 6s
      retries: 24
      start_period: 30s

  jobs:
    <<: *nexus
    restart: unless-stopped
    depends_on: *nexus-dependencies
    command: ["./bin/jobs"]

  model_runner:
    <<: *nexus
    restart: unless-stopped
    depends_on: *nexus-dependencies
    stop_grace_period: 35s
    command: ["./bin/model_runner"]

  rho:
    image: "${CYBROS_IMAGE_NAMESPACE:-jasl123}/cybros-rho:${CYBROS_IMAGE_TAG:-latest}"
    restart: unless-stopped
    stop_grace_period: 30s
    depends_on:
      nexus:
        condition: service_healthy
    environment:
      RHO_MODE: full
      RHO_HOME: /var/lib/rho
      RHO_TOOLS_ROOT: /home/runner
      RHO_NEXUS_URL: http://nexus
      RHO_ACCESS_PASSPHRASE: "${RHO_ACCESS_PASSPHRASE:?Missing rho passphrase}"
      RHO_TELEGRAM_BOT_TOKEN: "${RHO_TELEGRAM_BOT_TOKEN:-}"
    command: [server, --bind, "0.0.0.0", --port, "7777", --unsafe-plaintext]
    working_dir: /home/runner
    ports:
      - "${CYBROS_BIND:-127.0.0.1}:${CYBROS_RHO_PORT:-7777}:7777"
    volumes:
      - ./data/rho/home:/var/lib/rho
      - ./data/rho/work:/home/runner
    healthcheck:
      test: [CMD, curl, --fail, --silent, --max-time, "5", "http://127.0.0.1:7777/healthz"]
      interval: 5s
      timeout: 6s
      retries: 12
      start_period: 15s
    logging: *logging
CYBROS_PAYLOAD_EOF
    mv compose.yaml.new compose.yaml
  fi
  if [ ! -e cybros ]; then
    cat > cybros.new <<'CYBROS_PAYLOAD_EOF'
#!/bin/sh
# Local management for the installed stack. Configuration is Compose dotenv,
# never shell code: this script does not source an operator's environment file.
set -eu
umask 077

fail() { printf 'cybros: %s\n' "$*" >&2; exit 1; }
stack_dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
cd "$stack_dir"

compose() { docker compose --env-file .env --env-file secrets.env -f compose.yaml "$@"; }

container_exec() {
  if [ -t 0 ] && [ -t 1 ]; then
    compose exec "$@"
  else
    compose exec -T "$@"
  fi
}

prerequisites() {
  command -v docker >/dev/null 2>&1 || fail 'Docker is required. Install Docker Engine with Compose, or Docker Desktop, then retry.'
  docker compose version >/dev/null 2>&1 || fail 'Docker Compose v2 is required.'
  docker info >/dev/null 2>&1 || fail 'The Docker daemon is unavailable. Start Docker or select a working Docker context, then retry.'
  docker compose up --help | grep -q -- --wait-timeout || fail 'Update Docker Compose: up --wait-timeout is required.'
}

setting() {
  # Generated values use single-quoted dotenv literals, including dollar signs.
  # This reader is for display only; Docker Compose parses the actual settings.
  sed -n "s/^$1='\(.*\)'$/\1/p" .env | tail -n 1
}

write_setting() {
  case "$2" in *"'"*|*'
'*) fail "$1 must be a single line without single quotes" ;; esac
  printf "%s='%s'\n" "$1" "$2"
}

secret() {
  generated_secret=$(od -An -N32 -tx1 /dev/urandom | tr -d ' \n')
  [ "${#generated_secret}" -eq 64 ] || fail 'Could not read randomness from /dev/urandom'
  printf '%s' "$generated_secret"
}

initialize() {
  if [ ! -e secrets.env ] && [ -d data ]; then
    # Inspect only the top level: restored PostgreSQL children may belong to
    # its container user. An empty, pre-created data directory is a fresh install.
    for entry in data/* data/.[!.]* data/..?*; do
      if [ -e "$entry" ] || [ -L "$entry" ]; then
        fail 'Existing data has no secrets.env. Restore the original configuration from backup; new secrets cannot unlock this data.'
      fi
    done
  fi
  if { [ -e .env ] && [ ! -e secrets.env ]; } || { [ -e secrets.env ] && [ ! -e .env ]; }; then
    fail 'Only one configuration file exists. Restore the missing file from backup; secrets are never regenerated for an existing installation.'
  fi
  if [ ! -e .env ]; then
    {
      printf '# Compose configuration. Preserve secrets.env and the complete data/ directory.\n'
      write_setting CYBROS_PROJECT_NAME "${CYBROS_PROJECT_NAME:-cybros}"
      write_setting CYBROS_IMAGE_NAMESPACE "${CYBROS_IMAGE_NAMESPACE:-jasl123}"
      write_setting CYBROS_IMAGE_TAG "${CYBROS_IMAGE_TAG:-latest}"
      write_setting CYBROS_BIND "${CYBROS_BIND:-127.0.0.1}"
      write_setting CYBROS_NEXUS_PORT "${CYBROS_NEXUS_PORT:-3300}"
      write_setting CYBROS_RHO_PORT "${CYBROS_RHO_PORT:-7777}"
      write_setting CYBROS_NEXUS_URL "${CYBROS_NEXUS_URL:-http://localhost:${CYBROS_NEXUS_PORT:-3300}}"
      write_setting CYBROS_RHO_URL "${CYBROS_RHO_URL:-http://localhost:${CYBROS_RHO_PORT:-7777}}"
    } > .env.new
    mv .env.new .env
  fi
  if [ ! -e secrets.env ]; then
    {
      printf '# Private deployment secrets. Back up with the database; never rotate encryption keys by reinstalling.\n'
      for key in POSTGRES_PASSWORD SECRET_KEY_BASE ACTIVE_RECORD_ENCRYPTION__PRIMARY_KEY ACTIVE_RECORD_ENCRYPTION__DETERMINISTIC_KEY ACTIVE_RECORD_ENCRYPTION__KEY_DERIVATION_SALT NEXUS_SETUP_SECRET RHO_ACCESS_PASSPHRASE; do
        value=$(secret) || exit 1
        write_setting "$key" "$value"
      done
    } > secrets.env.new
    mv secrets.env.new secrets.env
  fi
  chmod 600 .env secrets.env
}

configured() {
  [ -f .env ] && [ -f secrets.env ] || fail 'Configuration is missing. Run the installer first; do not regenerate secrets for an existing database.'
  # Keep installation-file settings authoritative, even when this command is
  # launched from a shell used to install another stack.
  unset CYBROS_PROJECT_NAME CYBROS_IMAGE_NAMESPACE CYBROS_IMAGE_TAG CYBROS_BIND CYBROS_NEXUS_PORT CYBROS_RHO_PORT CYBROS_NEXUS_URL CYBROS_RHO_URL
  unset POSTGRES_PASSWORD SECRET_KEY_BASE ACTIVE_RECORD_ENCRYPTION__PRIMARY_KEY ACTIVE_RECORD_ENCRYPTION__DETERMINISTIC_KEY ACTIVE_RECORD_ENCRYPTION__KEY_DERIVATION_SALT NEXUS_SETUP_SECRET RHO_ACCESS_PASSPHRASE RHO_TELEGRAM_BOT_TOKEN
  compose config --quiet
}

start() {
  if ! compose up -d --wait --wait-timeout "${CYBROS_WAIT_TIMEOUT:-240}"; then
    compose ps --all >&2 || true
    fail 'Startup did not become healthy. Run ./cybros logs; configuration and data were retained.'
  fi
}

shell_quote() {
  printf "'"
  printf '%s' "$1" | sed "s/'/'\\\\''/g"
  printf "'"
}

working_directory() {
  printf '  cd '
  shell_quote "$stack_dir"
  printf '\n'
}

instructions() {
  [ -f .env ] && [ -f secrets.env ] || fail 'Configuration is missing. Run the installer first.'
  printf '\nNext steps\n'
  working_directory
  printf '\n1. Create your first account: %s/setup\n' "$(setting CYBROS_NEXUS_URL | sed 's:/*$::')"
  printf '   Create your first account using NEXUS_SETUP_SECRET from %s/secrets.env.\n' "$stack_dir"
  printf '\n2. Continue the model, connection and optional Telegram wizard:\n   ./cybros setup\n'
  printf '%s\n' '   Repeat a section with ./cybros setup model or ./cybros setup telegram.'
  printf '\nUse ./cybros status to check services, or ./cybros instructions to see these steps again.\n'
}

setup() {
  configured
  # The installer source may occupy stdin (curl | sh). The wizard must own a
  # real terminal, including Docker's TTY, without consuming shell source.
  if ! (exec 3<> /dev/tty) 2>/dev/null; then
    fail 'Setup needs an interactive terminal. Run ./cybros setup from a terminal; installed services and configuration were retained.'
  fi
  instructions
  if ! compose exec -e CMCTL_HOME=/var/lib/rho/cmctl rho rho setup \
    --nexus-url http://nexus --public-url "$(setting CYBROS_NEXUS_URL)" "$@" \
    </dev/tty >/dev/tty 2>&1; then
    fail 'Setup did not finish. Saved settings were retained; run ./cybros setup to continue.'
  fi
  reload_rho
  # Only the daemon polls Telegram. Start it before the optional first-user
  # step, so /start can report a numeric ID without a second getUpdates reader.
  if ! compose exec -e CMCTL_HOME=/var/lib/rho/cmctl rho rho setup telegram --finish \
    </dev/tty >/dev/tty 2>&1; then
    fail 'Telegram setup did not finish. rho is running; use ./cybros setup telegram to continue.'
  fi
  reload_rho
  printf '\nSetup complete. rho has reloaded its configuration.\n'
}

reload_rho() {
  # Reload through the existing supervisor: never start a second rho daemon
  # inside the container that owns the current Home.
  if ! compose up -d --no-deps --force-recreate --wait --wait-timeout "${CYBROS_WAIT_TIMEOUT:-240}" rho; then
    fail 'Settings were saved but rho did not become healthy. Run ./cybros logs rho, then ./cybros up.'
  fi
}

usage() {
  printf '%s\n' 'Usage: ./cybros init|install|setup [model|telegram]|instructions|up|status|logs [SERVICE]|stop|update [TAG]|connect|rho [ARGS...]|cmctl [ARGS...]|compose [ARGS...]'
  printf '%s\n' 'init initializes configuration only; it never pulls images or starts services.'
  printf '%s\n' 'install initializes missing configuration, pulls images and starts; reruns preserve existing files.'
  printf '%s\n' 'update pulls the configured tag, or selects latest/a Unix timestamp, then starts and checks health.'
  printf '%s\n' 'instructions prints setup and pairing steps without starting services.'
  printf '%s\n' 'setup configures providers, the default model and optional Telegram, then reloads rho.'
  printf '%s\n' 'stop preserves containers and data. compose exposes normal Docker Compose commands.'
}

action=${1:-help}
[ "$#" -eq 0 ] || shift
case "$action" in
  help|--help|-h) usage; exit 0 ;;
  instructions) instructions; exit 0 ;;
esac
prerequisites
case "$action" in
  init)
    initialize
    configured
    printf '\nConfiguration ready. Services have not been started.\n'
    working_directory
    printf '%s\n' '  ./cybros install' 'Use ./cybros up instead if the images are already available locally.'
    printf '%s\n' 'Then run ./cybros setup to configure your model and optional Telegram connection.'
    ;;
  install)
    [ "$#" -eq 0 ] || fail 'install takes no arguments'
    initialize
    configured
    compose pull
    start
    printf '\nCybros services are healthy.\n'
    instructions
    ;;
  up) configured; start ;;
  setup) setup "$@" ;;
  status) configured; compose ps --all ;;
  logs) configured; compose logs --tail 100 "$@" ;;
  stop) configured; compose stop ;;
  update)
    [ "$#" -le 1 ] || fail 'update accepts one tag'
    configured
    if [ "$#" -eq 1 ]; then
      case "$1" in latest) ;; ''|*[!0-9]*) fail 'tag must be latest or a Unix timestamp' ;; esac
      CYBROS_IMAGE_TAG=$1 compose pull
      awk -v tag="$1" '/^CYBROS_IMAGE_TAG=/{print "CYBROS_IMAGE_TAG=\047" tag "\047"; next} {print}' .env > .env.new
      mv .env.new .env
    else
      compose pull
    fi
    start
    ;;
  connect) configured; compose exec -T rho rho connect ;;
  rho) configured; compose exec -T rho rho "$@" ;;
  cmctl) configured; container_exec -e CMCTL_HOME=/var/lib/rho/cmctl rho cmctl "$@" ;;
  compose) configured; compose "$@" ;;
  *) usage >&2; fail "unknown command: $action" ;;
esac
CYBROS_PAYLOAD_EOF
    mv cybros.new cybros
  fi
  chmod 700 cybros
}
# Appended to the embedded templates by render.sh. Questions use /dev/tty,
# leaving stdin available for a piped installer.
install_fail() { printf 'Installer: %s\n' "$*" >&2; exit 1; }
install_cancel() { printf '\nInstallation cancelled. No files were changed.\n' >&2; exit 1; }

install_prompt() {
  printf '%s' "$1" >&3
  IFS= read -r answer <&3 || install_cancel
  [ -n "$answer" ] || answer=$2
}

install_port_valid() {
  case "$1" in ''|*[!0-9]*) return 1 ;; esac
  [ "${#1}" -le 5 ] && [ "$1" -ge 1 ] && [ "$1" -le 65535 ]
}

install_port() {
  while :; do
    install_prompt "$1 port [$2]: " "$2"
    if install_port_valid "$answer"; then
      # Decimal output avoids leading-zero interpretations in other tools.
      answer=$(printf '%s' "$answer" | sed 's/^0*//')
      return
    fi
    printf 'Enter a port from 1 to 65535.\n' >&3
  done
}

install_hostname() {
  while :; do
    install_prompt 'Server hostname or IPv4 address: ' ''
    case "$answer" in
      ''|*[!a-zA-Z0-9.-]*|[.-]*|*[.-]|0.0.0.0) printf 'Enter a hostname or IPv4 address, without a scheme, port or path.\n' >&3 ;;
      *) server_host=$answer; return ;;
    esac
  done
}

install_directory() {
  case "$install_dir" in
    '~') install_dir=$HOME ;;
    \~/*) install_dir=$HOME/${install_dir#\~/} ;;
    /*) ;;
    *) install_dir=$PWD/$install_dir ;;
  esac
  [ ! -e "$install_dir" ] || [ -d "$install_dir" ] || install_fail 'The installation path exists and is not a directory.'
  if [ -d "$install_dir" ]; then install_dir=$(CDPATH='' cd -- "$install_dir" && pwd); fi
  case "$install_dir" in '/'|*'
'*) install_fail 'Choose an installation directory other than /, on a single line.' ;; esac
}

install_prerequisites() {
  if ! command -v docker >/dev/null 2>&1; then
    case "$(uname -s)" in
      Darwin) printf '%s\n' 'Install Docker Desktop for Mac, open it, then run this installer again.' 'https://docs.docker.com/desktop/setup/install/mac-install/' >&2 ;;
      Linux) printf '%s\n' 'Install Docker Engine and the Docker Compose plugin for your Linux distribution, then run this installer again.' 'https://docs.docker.com/engine/install/' >&2 ;;
      *) printf '%s\n' 'Install Docker with Compose v2, then run this installer again.' 'https://docs.docker.com/get-started/get-docker/' >&2 ;;
    esac
    install_fail 'Docker was not found. This installer does not install Docker or run sudo.'
  fi
  docker compose version >/dev/null 2>&1 || install_fail 'Docker Compose v2 is missing. Install the Compose plugin (https://docs.docker.com/compose/install/) or update Docker Desktop, then retry.'
  docker info >/dev/null 2>&1 || install_fail 'Docker is not ready. Start Docker Desktop or Docker Engine, check your Docker context and permissions with docker info, then retry.'
  docker compose up --help | grep -q -- --wait-timeout || install_fail 'Update Docker Compose or Docker Desktop: compose up --wait-timeout is required.'
}

install_main() {
  set -eu
  umask 077
  install_dir=${CYBROS_INSTALL_DIR:-"$HOME/.local/share/cybros"}
  directory_set=${CYBROS_INSTALL_DIR:+yes}
  action=install
  unattended=no
  while [ "$#" -gt 0 ]; do
    case "$1" in
      --help|-h)
        printf '%s\n' 'Usage: sh install.sh [--dir DIRECTORY] [--no-start] [--yes]' 'Interactive setup uses /dev/tty, including when the script is piped to sh.' '--yes uses environment settings and defaults without questions.' '--no-start prepares configuration without pulling images or starting services.' 'Default directory: ~/.local/share/cybros. Requires Docker with Compose v2.'
        return 0
        ;;
      --dir) [ "$#" -ge 2 ] && [ -n "$2" ] || install_fail '--dir requires one nonempty directory'; install_dir=$2; directory_set=yes; shift 2 ;;
      --no-start) action=init; shift ;;
      --yes) unattended=yes; shift ;;
      *) install_fail 'Usage: sh install.sh [--dir DIRECTORY] [--no-start] [--yes]' ;;
    esac
  done

  printf '\nCybros setup\n\n[1/5] Checking Docker\n'
  install_prerequisites
  printf '\n[2/5] Installation directory\n'
  install_directory
  if [ ! -e "$install_dir/.env" ] && [ ! -e "$install_dir/secrets.env" ] && [ "$unattended" = no ]; then
    # Test in a subshell first: a failed special-builtin redirection can exit sh.
    (exec 3<>/dev/tty) 2>/dev/null || install_fail 'Interactive setup needs a terminal. Run with --yes to use environment settings and defaults.'
    exec 3<>/dev/tty
    trap 'install_cancel' HUP INT TERM
    if [ -z "$directory_set" ]; then
      install_prompt "Installation directory [$install_dir]: " "$install_dir"
      install_dir=$answer
      install_directory
    fi
  fi
  printf 'Directory: %s\n' "$install_dir"

  if [ -e "$install_dir/.env" ] || [ -e "$install_dir/secrets.env" ]; then
    printf '\n[3/5] Keeping existing configuration\n'
    printf '%s\n' 'Existing configuration, secrets and data will be preserved. Setup questions are skipped.'
  else
    printf '\n[3/5] Network access\n'
    server_host=localhost
    if [ "$unattended" = no ]; then
      if [ -n "${CYBROS_BIND:-}${CYBROS_NEXUS_URL:-}${CYBROS_RHO_URL:-}" ]; then
        printf '%s\n' 'Using the network settings supplied in the environment.'
        if [ -z "${CYBROS_NEXUS_URL:-}" ] || [ -z "${CYBROS_RHO_URL:-}" ]; then
          case "${CYBROS_BIND:-127.0.0.1}:${CYBROS_NEXUS_URL:-}${CYBROS_RHO_URL:-}" in
            127.0.0.1:) ;;
            *) printf '%s\n' 'Choose the browser hostname for any URL not supplied above.'; install_hostname ;;
          esac
        fi
      else
        printf '%s\n' '1) This computer only (default)' '2) Home server or LAN'
        while :; do
          install_prompt 'Access [1]: ' 1
          case "$answer" in 1|2) break ;; *) printf 'Choose 1 or 2.\n' >&3 ;; esac
        done
        if [ "$answer" = 2 ]; then
          install_hostname
          CYBROS_BIND=0.0.0.0
          printf '%s\n' 'Both services will listen on all interfaces. Use these HTTP addresses on your trusted LAN.'
        fi
      fi
      if [ -z "${CYBROS_NEXUS_PORT:-}" ]; then
        install_port Nexus 3300
        CYBROS_NEXUS_PORT=$answer
      fi
      if [ -z "${CYBROS_RHO_PORT:-}" ]; then
        while :; do
          install_port rho 7777
          [ "$answer" != "$CYBROS_NEXUS_PORT" ] && break
          printf 'Use a different port from Nexus.\n' >&3
        done
        CYBROS_RHO_PORT=$answer
      fi
    fi
    CYBROS_BIND=${CYBROS_BIND:-127.0.0.1}
    CYBROS_NEXUS_PORT=${CYBROS_NEXUS_PORT:-3300}
    CYBROS_RHO_PORT=${CYBROS_RHO_PORT:-7777}
    install_port_valid "$CYBROS_NEXUS_PORT" || install_fail 'CYBROS_NEXUS_PORT must be a port from 1 to 65535.'
    install_port_valid "$CYBROS_RHO_PORT" || install_fail 'CYBROS_RHO_PORT must be a port from 1 to 65535.'
    [ "$CYBROS_NEXUS_PORT" -ne "$CYBROS_RHO_PORT" ] || install_fail 'Nexus and rho need different ports.'
    CYBROS_NEXUS_URL=${CYBROS_NEXUS_URL:-http://$server_host:$CYBROS_NEXUS_PORT}
    CYBROS_RHO_URL=${CYBROS_RHO_URL:-http://$server_host:$CYBROS_RHO_PORT}
    export CYBROS_BIND CYBROS_NEXUS_PORT CYBROS_RHO_PORT CYBROS_NEXUS_URL CYBROS_RHO_URL
  fi

  printf '\n[4/5] Review installation\n'
  printf 'Directory: %s\nData:      %s/data\n' "$install_dir" "$install_dir"
  if [ ! -e "$install_dir/.env" ] && [ ! -e "$install_dir/secrets.env" ]; then
    printf 'Nexus:     %s\nrho:       %s\nBind:      %s\nImages:    %s/cybros-{nexus,rho}:%s\n' "$CYBROS_NEXUS_URL" "$CYBROS_RHO_URL" "$CYBROS_BIND" "${CYBROS_IMAGE_NAMESPACE:-jasl123}" "${CYBROS_IMAGE_TAG:-latest}"
    if [ "$unattended" = no ]; then
      if [ "$action" = init ]; then question='Create configuration? [Y/n]: '; else question='Install and start Cybros? [Y/n]: '; fi
      while :; do
        install_prompt "$question" y
        case "$answer" in y|Y|[Yy][Ee][Ss]) break ;; n|N|[Nn][Oo]) install_cancel ;; *) printf 'Answer yes or no.\n' >&3 ;; esac
      done
    fi
  fi
  trap - HUP INT TERM
  mkdir -p "$install_dir"
  install_dir=$(CDPATH='' cd -- "$install_dir" && pwd)
  [ "$install_dir" != / ] || install_fail 'Choose an installation directory other than /.'
  chmod 700 "$install_dir"
  if [ -e "$install_dir/cybros" ] || [ -e "$install_dir/compose.yaml" ]; then
    printf '%s\n' 'Keeping the existing cybros manager and Compose file, including local changes.'
  fi
  (
    cd "$install_dir"
    install_payload
  )
  if [ "$action" = init ]; then
    printf '\n[5/5] Preparing configuration\n'
  else
    printf '\n[5/5] Pulling images and waiting for healthy services\n'
  fi
  "$install_dir/cybros" "$action" </dev/null
  if [ "$action" = install ] && [ "$unattended" = no ] && (exec 3<> /dev/tty) 2>/dev/null; then
    "$install_dir/cybros" setup </dev/tty >/dev/tty 2>&1
  fi
}

install_main "$@"
