#!/bin/sh
# Development-only renderer; the delivered install.sh is completely self-contained.
set -eu
here=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
generated=$(mktemp "${TMPDIR:-/tmp}/cybros-installer.XXXXXX")
trap 'rm -f "$generated"' 0 HUP INT TERM
{
  printf '%s\n' '#!/bin/sh' '# Generated by install/stack/render.sh; edit the adjacent templates.' 'install_payload() {'
  for file in compose.yaml cybros setup.rb; do
    printf "  if [ ! -e %s ]; then\n    cat > %s.new <<'CYBROS_PAYLOAD_EOF'\n" "$file" "$file"
    cat "$here/$file"
    printf 'CYBROS_PAYLOAD_EOF\n    mv %s.new %s\n  fi\n' "$file" "$file"
  done
  printf '%s\n' '  chmod 700 cybros' '  chmod 644 setup.rb' '}'
  cat "$here/bootstrap.sh"
} > "$generated"
if [ "${1:-}" = --check ]; then
  cmp "$generated" "$here/install.sh" || { printf '%s\n' 'Run install/stack/render.sh to update install.sh.' >&2; exit 1; }
else
  cp "$generated" "$here/install.sh"
  chmod 755 "$here/install.sh"
fi
