# ---------------------------------------------------------------------------
# Step: the wrapper and the shims. The environment is rho's own process's:
# PATH (the toolchain, for rho and every tool child — rg, fd, jq, uv shadow
# the person's inside the model's shell, by design), the prefix, the locale
# rule, the bootsnap cache root, and Ruby's spelling of "load the app from
# the prefix". Nothing Playwright- or uv-specific: the driver is found from
# RHO_PREFIX at rho's own spawn site, the browsers dir is set inside
# bin/rho-playwright, uv is unconfigured.
# THE TRUST STORE: the portable Ruby's
# OpenSSL is static and reads its roots from the path its builder had
# (/home/linuxbrew/.linuxbrew/Cellar/portable-openssl/…/cert.pem), absent
# on every other machine — so a Ruby-side HTTPS (rho-web-tools' fetch, an http
# MCP server, MCP OAuth, `rho update`'s own fetches) verifies nothing.
# When that compiled path is absent the host's bundle is probed here — the
# distros' spellings, Go's crypto/x509 list — and baked into the wrapper
# as SSL_CERT_FILE (OpenSSL's own override, read by every build), which
# the daemon and every tool child inherit; a person's own value wins.
# Prints the path, or nothing: `rho doctor`'s tls row says what came of it.
trust_store_file() {
  local compiled candidate
  compiled=$( ( scrub_ruby_env; exec "$RUBY_DIR/bin/ruby" -ropenssl -e 'print OpenSSL::X509::DEFAULT_CERT_FILE' ) 2>/dev/null )
  [ -n "$compiled" ] && [ -r "$compiled" ] && return 0
  for candidate in /etc/ssl/certs/ca-certificates.crt /etc/pki/tls/certs/ca-bundle.crt /etc/ssl/ca-bundle.pem \
      /etc/pki/tls/cacert.pem /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem /etc/ssl/cert.pem; do
    if [ -r "$candidate" ]; then printf "%s" "$candidate"; return 0; fi
  done
  warn "no CA bundle found on this host (the portable OpenSSL's own path ${compiled:-is unknown and} is absent): Ruby-side HTTPS cannot verify certificates until one is installed (ca-certificates) — rho doctor reports it"
}

write_wrapper() {
  local name="$1" entry="$2" bootsnap_default trust_store trust_store_line=""
  if [ -n "$BAKED_BOOTSNAP_CACHE" ]; then
    bootsnap_default="$BAKED_BOOTSNAP_CACHE"
  else
    # shellcheck disable=SC2016
    bootsnap_default='${RHO_HOME:-$HOME/.rho}/cache/bootsnap'
  fi
  ohai "Writing $PREFIX/bin/$name"
  [ -n "$DRY_RUN" ] && return 0
  trust_store=$(trust_store_file)
  if [ -n "$trust_store" ]; then
    ohai "Naming the trust store $trust_store in bin/$name (the portable OpenSSL's compiled path is absent)"
    # shellcheck disable=SC2016
    trust_store_line='export SSL_CERT_FILE="${SSL_CERT_FILE:-'"$trust_store"'}"'
  fi
  mkdir -p "$PREFIX/bin"
  cat > "$PREFIX/bin/$name.new" <<WRAPPER
#!/bin/bash
# generated by rho's install.sh — RHO_PREFIX is baked in; \`rho update\` rewrites this file.
RHO_PREFIX="$PREFIX"
export RHO_PREFIX
# UTF-8 before Ruby starts, only when nothing governs (Rho::Locale's rule):
# ARGV is tagged with the locale encoding before exe/rho's first line runs.
if [ -z "\${LC_ALL:-}\${LC_CTYPE:-}\${LANG:-}" ]; then export LANG=C.UTF-8; fi
export PATH="\$RHO_PREFIX/bin:\$PATH"
export RHO_BOOTSNAP_CACHE_DIR="\${RHO_BOOTSNAP_CACHE_DIR:-$bootsnap_default}"
$trust_store_line
unset RUBYOPT RUBYLIB GEM_HOME GEM_PATH BUNDLER_VERSION BUNDLE_BIN_PATH BUNDLER_SETUP
# shellcheck disable=SC2046
for rho_name in \$(compgen -v BUNDLE_ 2>/dev/null); do unset "\$rho_name"; done
unset rho_name
export BUNDLE_GEMFILE="\$RHO_PREFIX/current/$RHO_APP_GEMFILE"
export BUNDLE_PATH="\$RHO_PREFIX/current/vendor/bundle"
export BUNDLE_DEPLOYMENT=1
export BUNDLE_WITHOUT="$RHO_APP_BUNDLE_WITHOUT"
exec "\$RHO_PREFIX/ruby/current/bin/ruby" -rbundler/setup "\$RHO_PREFIX/current/$entry" "\$@"
WRAPPER
  chmod 755 "$PREFIX/bin/$name.new"
  mv -f "$PREFIX/bin/$name.new" "$PREFIX/bin/$name"
}

# The driver: Node + playwright-core pinned to the gem's version; the
# browsers directory scoped to THIS process and its Chromium, never to a
# tool child.
write_playwright_wrapper() {
  ohai "Writing $PREFIX/bin/rho-playwright"
  [ -n "$DRY_RUN" ] && return 0
  mkdir -p "$PREFIX/bin"
  cat > "$PREFIX/bin/rho-playwright" <<WRAPPER
#!/bin/bash
# generated by rho's install.sh: the Playwright driver rho's browser extension speaks to.
RHO_PREFIX="$PREFIX"
export PLAYWRIGHT_BROWSERS_PATH="\${PLAYWRIGHT_BROWSERS_PATH:-\$RHO_PREFIX/browsers}"
exec "\$RHO_PREFIX/lib/playwright/node/bin/node" "\$RHO_PREFIX/lib/playwright/package/cli.js" "\$@"
WRAPPER
  chmod 755 "$PREFIX/bin/rho-playwright"
}

# `python3` for a model's `python3 -m http.server`, only when the host has
# none: uv runs (and, once, downloads) a CPython into uv's own default dir.
write_python_shim() {
  [ -x "$PREFIX/bin/uv" ] || return 0
  if have python3 && [ "$(command -v python3)" != "$PREFIX/bin/python3" ]; then
    rm -f "$PREFIX/bin/python3"
    return 0
  fi
  ohai "Writing $PREFIX/bin/python3 (this host has no python3; uv provides one on first use)"
  [ -n "$DRY_RUN" ] && return 0
  cat > "$PREFIX/bin/python3" <<SHIM
#!/bin/bash
# generated by rho's install.sh: a python3 for the model's shell, from uv, because this host had none.
exec "$PREFIX/bin/uv" run --no-project --python 3.13 python "\$@"
SHIM
  chmod 755 "$PREFIX/bin/python3"
}

# ---------------------------------------------------------------------------
# Step: the launcher and the PATH line (printed unless --modify-path).
# shellcheck disable=SC2016
RC_LINE='export PATH="$HOME/.local/bin:$PATH"   # rho'
rc_file() {
  case "${SHELL:-}" in
    */zsh) printf "%s" "$HOME/.zprofile" ;;
    */bash) if [ "$OS" = "darwin" ]; then printf "%s" "$HOME/.bash_profile"; else printf "%s" "$HOME/.bashrc"; fi ;;
    */fish) printf "%s" "$HOME/.config/fish/config.fish" ;;
    *) printf "%s" "$HOME/.profile" ;;
  esac
}

link_launcher() {
  local name launcher
  [ -n "$DRY_RUN" ] && return 0
  mkdir -p "$LAUNCHER_DIR"
  for name in rho cmctl; do
    launcher="$LAUNCHER_DIR/$name"
    ohai "Linking $launcher -> $PREFIX/bin/$name"
    if [ -e "$launcher" ] && [ ! -L "$launcher" ]; then
      warn "$launcher exists and is not a symlink; leaving it alone (run $PREFIX/bin/$name directly, or remove it and re-run)"
      continue
    fi
    ln -sfn "$PREFIX/bin/$name" "$launcher" || abort "rho install: could not link $launcher"
  done
}

RC_WRITTEN=""
launcher_on_path() {
  # shellcheck disable=SC2031
  case ":$PATH:" in
    *":$LAUNCHER_DIR:"*) return 0 ;;
    *) return 1 ;;
  esac
}
offer_path_line() {
  local file line
  if launcher_on_path; then
    return 0
  fi
  file=$(rc_file)
  if [ "${SHELL:-}" != "${SHELL%fish}" ]; then
    line="fish_add_path $LAUNCHER_DIR   # rho"
  else
    line="export PATH=\"$LAUNCHER_DIR:\$PATH\"   # rho"
  fi
  if [ -n "$MODIFY_PATH" ]; then
    ohai "Adding the PATH line to $file"
    [ -n "$DRY_RUN" ] && return 0
    mkdir -p "$(dirname "$file")"
    touch "$file"
    if ! grep -qxF "$line" "$file"; then
      printf "\n%s\n" "$line" >> "$file"
    fi
    RC_WRITTEN="$file"
    RC_LINE="$line"
  else
    RC_LINE="$line"
  fi
}

# ---------------------------------------------------------------------------
# Step: the receipts — receipt.json for rho (`doctor`, `Rho::Install`) and
# receipt.sh for this script (bash 3.2 reads no JSON) — and the copies.
write_receipts() {
  local now rc_file_recorded rc_line_recorded
  now=$(date -u +%Y-%m-%dT%H:%M:%SZ)
  [ -n "$DRY_RUN" ] && return 0
  # The rc line this run wrote, else the one a previous run recorded.
  if [ -n "$RC_WRITTEN" ]; then
    rc_file_recorded="$RC_WRITTEN"; rc_line_recorded="$RC_LINE"
  else
    rc_file_recorded="$RHO_RECEIPT_RC_FILE"; rc_line_recorded="$RHO_RECEIPT_RC_LINE"
  fi
  mkdir -p "$PREFIX/libexec"
  if ! [ "$0" -ef "$PREFIX/libexec/install.sh" ]; then
    cp -f "$0" "$PREFIX/libexec/install.sh"
    chmod 755 "$PREFIX/libexec/install.sh"
  fi
  if [ -f "$(dirname "$0")/docker-entrypoint" ] && ! [ "$(dirname "$0")/docker-entrypoint" -ef "$PREFIX/libexec/docker-entrypoint" ]; then
    cp -f "$(dirname "$0")/docker-entrypoint" "$PREFIX/libexec/docker-entrypoint"
    chmod 755 "$PREFIX/libexec/docker-entrypoint"
  fi
  printf "%s\n" "$RHO_MANIFEST_JSON" > "$PREFIX/manifest.json"
  cat > "$RECEIPT_JSON.new" <<RECEIPT
{
  "receipt_version": 1,
  "installed_at": "$now",
  "manifest_generated": "$RHO_MANIFEST_GENERATED",
  "profile": "$PROFILE",
  "platform": "$PLATFORM",
  "prefix": "$PREFIX",
  "source_path": "$APP_SOURCE_PATH",
  "app": { "version": "$APP_VERSION", "commit": "$APP_COMMIT" },
  "ruby": { "version": "$RUBY_VERSION", "sha256": "$RUBY_SHA", "bundler": "$RHO_RUBY_BUNDLER" },
  "current": "$VERSION_NAME",
  "previous": "$PREVIOUS",
  "launcher": "$LAUNCHER",
  "rc_file": "$rc_file_recorded",
  "rc_line": "$(printf "%s" "$rc_line_recorded" | sed 's/"/\\"/g')",
  "bootsnap_cache": "$BAKED_BOOTSNAP_CACHE",
  "tools": { $RECEIPT_TOOLS_JSON }
}
RECEIPT
  mv -f "$RECEIPT_JSON.new" "$RECEIPT_JSON"
  {
    printf "# written by install.sh; the same facts as receipt.json, for bash\n"
    printf "RHO_RECEIPT_VERSION=1\nRHO_RECEIPT_INSTALLED_AT=\"%s\"\nRHO_RECEIPT_PROFILE=\"%s\"\nRHO_RECEIPT_PLATFORM=\"%s\"\n" "$now" "$PROFILE" "$PLATFORM"
    printf "RHO_RECEIPT_SOURCE_PATH=\"%s\"\n" "$APP_SOURCE_PATH"
    printf "RHO_RECEIPT_APP_VERSION=\"%s\"\nRHO_RECEIPT_APP_COMMIT=\"%s\"\n" "$APP_VERSION" "$APP_COMMIT"
    printf "RHO_RECEIPT_RUBY_VERSION=\"%s\"\nRHO_RECEIPT_RUBY_SHA256=\"%s\"\nRHO_RECEIPT_BUNDLER=\"%s\"\n" "$RUBY_VERSION" "$RUBY_SHA" "$RHO_RUBY_BUNDLER"
    printf "RHO_RECEIPT_CURRENT=\"%s\"\nRHO_RECEIPT_PREVIOUS=\"%s\"\nRHO_RECEIPT_LAUNCHER=\"%s\"\n" "$VERSION_NAME" "$PREVIOUS" "$LAUNCHER"
    printf "RHO_RECEIPT_RC_FILE=\"%s\"\nRHO_RECEIPT_RC_LINE='%s'\n" "$rc_file_recorded" "$rc_line_recorded"
    printf "RHO_RECEIPT_BOOTSNAP_CACHE=\"%s\"\n" "$BAKED_BOOTSNAP_CACHE"
    printf "RHO_RECEIPT_TOOLS=\"%s\"%s\n" "${RECORDED_TOOLS:-}" "$RECEIPT_TOOLS_SH"
  } > "$RECEIPT_SH.new"
  mv -f "$RECEIPT_SH.new" "$RECEIPT_SH"
}

# ---------------------------------------------------------------------------
# Step: prewarm (the bootsnap cold boot lands here, not in the first verb),
# then the doctor.
prewarm() {
  ohai "$PREFIX/bin/rho" version
  [ -n "$DRY_RUN" ] && return 0
  "$PREFIX/bin/rho" version || abort "rho install: the installed rho does not run"
  "$PREFIX/bin/rho" help >/dev/null 2>&1 || warn "rho help did not run cleanly"
}

run_doctor() {
  ohai "$PREFIX/bin/rho" doctor
  [ -n "$DRY_RUN" ] && return 0
  "$PREFIX/bin/rho" doctor || true
}

CHROMIUM_APT_LINE=""
epilogue() {
  printf "\n%sInstallation successful!%s\n\n" "$tty_bold" "$tty_reset"
  if ! launcher_on_path; then
    printf "Add rho to your PATH by running (or add the line to %s):\n  %s\n\n" "$(rc_file)" "$RC_LINE"
  fi
  if [ -n "$CHROMIUM_APT_LINE" ]; then
    printf "The Chromium shell needs shared libraries this script cannot install (root):\n  %s\n\n" "$CHROMIUM_APT_LINE"
  fi
  if [ "${RHO_MODE:-full}" = runner ]; then
    printf "Next: pair this runner with a Nexus:\n  rho connect --nexus-url https://nexus.example\n"
  else
    printf "Next: configure your model and optional Telegram connection:\n  rho setup --nexus-url https://nexus.example\n"
  fi
  printf "Then: rho server   (the daemon); rho doctor at any time; rho update; rho uninstall\n"
  if [ "$MODE" = install ] && [ -z "${NONINTERACTIVE-}" ] && [ "${RHO_MODE:-full}" != runner ]; then
    "$PREFIX/bin/rho" setup </dev/tty || warn "Setup did not finish; saved settings were retained. Run rho setup to continue."
  fi
}
